import Link from "next/link";
import { ArrowDown, ArrowUpRight, Github, Linkedin, Mail, MapPin, Sparkles, Terminal, Code2, Database, Server, Send, ExternalLink } from "lucide-react";
import { connectDB } from "@/lib/mongodb";
import Project from "@/models/Project";
import Post from "@/models/Post";
import { demoProjects, demoPosts, skills } from "@/lib/site-data";
import SiteHeader from "@/app/components/SiteHeader";
import Reveal from "@/app/components/Reveal";
import ContactForm from "@/app/components/ContactForm";

export const dynamic = "force-dynamic";

async function getContent() {
  try {
    await connectDB();
    const [projects, posts] = await Promise.all([
      Project.find({ featured: true }).sort({ order: 1, createdAt: -1 }).limit(4).lean(),
      Post.find({ published: true }).sort({ publishedAt: -1 }).limit(3).lean(),
    ]);
    return { projects: projects.length ? projects.map(p => ({ ...p, _id: String(p._id) })) : demoProjects, posts: posts.length ? posts.map(p => ({ ...p, _id: String(p._id) })) : demoPosts };
  } catch {
    return { projects: demoProjects, posts: demoPosts };
  }
}

const timeline = [
  { year: "2024 — Present", role: "Full-Stack Developer", company: "Independent / Product Builds", desc: "Building production-minded web applications with Next.js, TypeScript, MongoDB and thoughtful UX systems." },
  { year: "2023 — 2024", role: "Developer / BPO → Engineering", company: "Cognizant", desc: "Started professionally in BPO and deliberately pivoted toward software engineering through hands-on product development." },
];

export default async function Home() {
  const { projects, posts } = await getContent();
  return <main className="min-h-screen overflow-hidden bg-[#09080d] border border-red-500">
    <SiteHeader />

    <section className="mx-auto flex h-screen max-w-7xl items-start px-5 pb-20 md:px-8 border">
      <div className="grid w-full items-center gap-10 lg:grid-cols-[1.2fr_.8fr]">
        <div className="relative z-10">
          <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-[#9b5cff]/30 bg-[#9b5cff]/10 px-3 py-1.5 text-[11px] uppercase tracking-[.22em] text-[#ceb6ff]"><span className="h-2 w-2 animate-pulse rounded-full bg-[#d6ff3f]" /> available for select builds</div>
          <p className="hand mb-2 rotate-[-2deg] text-2xl text-[#d6ff3f]">Hey, I'm Saksham.</p>
          <h1 className="max-w-5xl text-2xl font-black leading-[.88] tracking-[-.07em] text-gradient">I build<br /><span className="underline-acid">modern</span><br />web experiences.</h1>
          <p className="mt-8 max-w-2xl text-base leading-7 text-white/[.55] md:text-lg">Transforming bold ideas into scalable, production-ready software. Full-stack developer specializing in building fast, scalable, and intuitive web applications — bridging robust backend architecture with modern frontend design.</p>
          <div className="mt-9 flex flex-wrap gap-3"><a data-cursor href="#work" className="group inline-flex items-center gap-2 rounded-full bg-[#d6ff3f] px-6 py-3 text-sm font-bold text-black shadow-acid">See the work <ArrowUpRight size={16} className="transition group-hover:translate-x-1 group-hover:-translate-y-1" /></a><a data-cursor href="/resume-demo.txt" download className="inline-flex items-center gap-2 rounded-full border border-white/[.1] px-6 py-3 text-sm text-white/[.75] hover:border-white/[.2] hover:bg-white/[.05]"><span>Download résumé</span></a></div>
          <div className="mt-9 flex items-center gap-5 text-white/[.35]"><a data-cursor href="https://github.com/saksham-pahadi" aria-label="GitHub"><Github size={18} /></a><a data-cursor href="https://linkedin.com/in/saksham-demo" aria-label="LinkedIn"><Linkedin size={18} /></a><a data-cursor href="mailto:hello@saksham.dev" aria-label="Email"><Mail size={18} /></a></div>
        </div>
        <div className="relative mx-auto h-[480px] w-full max-w-[480px] lg:h-[600px]">
          <div className="absolute inset-8 rounded-[44%_56%_42%_58%/45%_44%_56%_55%] bg-[#6d2bff]/20 blur-3xl" />
          <div className="absolute right-0 top-6 rounded-2xl border border-white/[.1] bg-white/[.03] px-4 py-3 shadow-glow backdrop-blur"><p className="mono text-[10px] uppercase tracking-[.25em] text-white/[.35]">stack.txt</p><p className="mt-1 text-sm">Next.js · TypeScript · MongoDB</p></div>
          <div className="absolute bottom-14 left-0 z-10 rounded-2xl border border-white/[.1] bg-[#111017]/90 px-4 py-3 shadow-glow backdrop-blur"><p className="mono text-[10px] uppercase tracking-[.25em] text-white/[.35]">status</p><p className="mt-1 flex items-center gap-2 text-sm"><span className="h-2 w-2 rounded-full bg-[#d6ff3f]" /> shipping ideas</p></div>
          <div className="absolute left-1/2 top-1/2 grid h-[340px] w-[280px] -translate-x-1/2 -translate-y-1/2 rotate-[-5deg] place-items-center rounded-[46%_54%_43%_57%/44%_46%_54%_56%] border border-white/[.1] bg-gradient-to-br from-[#1a1325] via-[#17111f] to-[#0d0b11] shadow-[0_40px_100px_rgba(0,0,0,.55)] animate-float md:h-[420px] md:w-[350px]">
            <svg viewBox="0 0 350 420" className="h-[90%] w-[90%]" role="img" aria-label="Abstract developer avatar illustration"><path d="M56 172c-6-92 59-138 134-138 85 0 114 53 103 128l-12 93c-7 55-41 100-102 108-58 8-106-28-116-87z" fill="#f4c7a6" /><path d="M51 174c-13-75 18-126 77-143 67-20 143 15 166 66-21-12-40-20-61-21 13 23 12 36 9 52-18-31-58-45-87-35-19 7-37 20-56 46-10 14-26 25-48 35z" fill="#111017" /><path d="M102 191c12-22 28-32 46-32M219 159c18 0 31 9 41 22" fill="none" stroke="#151017" strokeWidth="7" strokeLinecap="round" /><circle cx="132" cy="188" r="8" fill="#151017" /><circle cx="241" cy="188" r="8" fill="#151017" /><path d="M152 231c20 19 43 21 67 3" fill="none" stroke="#151017" strokeWidth="7" strokeLinecap="round" /><path d="M90 300c48-32 118-31 164 5l-12 85H111z" fill="#7e45ef" /><path d="M112 305l58 39 57-38" fill="none" stroke="#d6ff3f" strokeWidth="5" /><circle cx="214" cy="350" r="14" fill="#d6ff3f" /><path d="M220 346l16-8-8 15 13 8-17 1z" fill="#151017" /></svg>
          </div>
          <div className="absolute left-7 top-1/3 -rotate-12 text-[#9b5cff]"><Sparkles size={56} /></div><div className="absolute bottom-0 right-4 rotate-12 text-[#d6ff3f]"><Terminal size={54} /></div>
        </div>
      </div>
      <a href="#work" className="absolute bottom-8 left-1/2 flex -translate-x-1/2 flex-col items-center gap-2 text-[10px] uppercase tracking-[.28em] text-white/[.3]"><ArrowDown size={16} className="animate-bounce" /> scroll</a>
      <div className="grid-bg absolute inset-0 -z-0" />
      <div className="pointer-events-none absolute left-[-10%] top-[-15%] h-[420px] w-[420px] rounded-full bg-[#6d2bff]/15 blur-3xl" /><div className="pointer-events-none absolute right-[-10%] bottom-[-10%] h-[420px] w-[420px] rounded-full bg-[#9b5cff]/10 blur-3xl" />
    </section>

    <div className="border-y border-white/[.06] bg-white/[.015] py-4 border border-red-500"><div className="flex w-[200%] animate-marquee gap-10 whitespace-nowrap text-xs uppercase tracking-[.35em] text-white/[.3]">{Array.from({ length: 12 }, (_, i) => <span key={i}>Next.js ✦ TypeScript ✦ MongoDB ✦ Product thinking ✦ Clean APIs ✦ UI systems ✦</span>)}</div></div>

    <section id="work" className="mx-auto max-w-7xl px-5 py-28 md:px-8 border border-green-500">
      <Reveal><div className="flex items-end justify-between gap-6"><div><p className="mono text-xs uppercase tracking-[.28em] text-[#9b5cff]">01 / selected work</p><h2 className="mt-3 text-4xl font-bold tracking-tight md:text-6xl">Things I've shipped.</h2></div><Link href="/projects" className="hidden rounded-full border border-white/[.1] px-5 py-2.5 text-xs text-white/[.65] hover:bg-white/[.05] md:inline-flex">All projects <ArrowUpRight size={14} /></Link></div></Reveal>
      <div className="mt-10 grid gap-5 md:grid-cols-2">{projects.map((p: any, index: number) => <Reveal key={p._id} delay={index * .06}><article className="group overflow-hidden rounded-[28px] border border-white/[.07] bg-[#111017] transition hover:-translate-y-1 hover:border-[#9b5cff]/35 hover:shadow-glow"><div className="relative aspect-[16/10] overflow-hidden bg-[#0c0b10]"><img src={p.image || `/project-${(index % 4) + 1}.svg`} alt={p.title} className="h-full w-full object-cover transition duration-500 group-hover:scale-[1.03]" /><div className="absolute inset-0 bg-gradient-to-t from-[#111017] via-transparent to-transparent opacity-80" /><div className="absolute left-4 top-4 rounded-full border border-white/[.1] bg-black/30 px-3 py-1 text-[10px] uppercase tracking-[.18em] backdrop-blur">0{index + 1}</div></div><div className="p-6"><div className="flex items-start justify-between gap-4"><h3 className="text-2xl font-semibold tracking-tight">{p.title}</h3><ArrowUpRight size={20} className="text-white/[.3] transition group-hover:text-white" /></div><p className="mt-3 text-sm leading-6 text-white/[.48]">{p.description}</p><div className="mt-5 flex flex-wrap gap-2">{p.stack?.map((s: string) => <span key={s} className="rounded-full border border-white/[.08] px-2.5 py-1 text-[10px] text-white/[.5]">{s}</span>)}</div></div></article></Reveal>)}</div>
    </section>

    <section id="about" className="mx-auto max-w-7xl px-5 pb-28 md:px-8 border border-blue-500"><div className="grid gap-7 lg:grid-cols-[.8fr_1.2fr]"><Reveal><div className="relative h-full min-h-[360px] overflow-hidden rounded-[34px] border border-white/[.07] bg-[#111017] p-7"><div className="absolute -right-16 -top-16 h-48 w-48 rounded-full border border-[#9b5cff]/20" /><div className="absolute -bottom-20 -left-10 h-44 w-44 rounded-full border border-[#d6ff3f]/20" /><p className="mono text-xs text-white/[.3]">ABOUT_ME.md</p><div className="mt-10 text-[70px] font-black leading-none tracking-[-.08em] text-[#9b5cff]">10×</div><p className="mt-4 max-w-xs text-xl font-semibold">curiosity over comfort.</p><p className="mt-4 text-sm leading-6 text-white/[.45]">I like products that feel simple on the surface but are thoughtfully engineered underneath.</p><div className="absolute bottom-7 right-7 -rotate-6 rounded-2xl border border-[#d6ff3f]/25 bg-[#d6ff3f]/10 px-4 py-3 font-mono text-xs text-[#e9ff9a]">ship → learn → iterate</div></div></Reveal><Reveal delay={.06}><div className="rounded-[34px] border border-white/[.07] bg-[#111017] p-7 md:p-9"><p className="mono text-xs uppercase tracking-[.24em] text-[#d6ff3f]">the human behind the stack</p><h2 className="mt-5 max-w-3xl text-3xl font-semibold leading-tight md:text-5xl">I bridge robust backend architecture with interfaces that feel effortless.</h2><p className="mt-7 max-w-3xl text-sm leading-7 text-white/[.5] md:text-base">{`I'm Saksham, a full-stack developer focused on modern web products. My sweet spot is the space between system design and polish: clean APIs, durable data models, responsive UI, and enough motion to make the product feel alive without getting in the user's way.`}</p><div className="mt-8 grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border border-white/[.07] bg-black/10 p-4"><Code2 className="text-[#9b5cff]" /><p className="mt-4 text-sm font-medium">Product UI</p><p className="mt-1 text-xs text-white/[.35]">React · Next.js · Tailwind</p></div><div className="rounded-2xl border border-white/[.07] bg-black/10 p-4"><Server className="text-[#d6ff3f]" /><p className="mt-4 text-sm font-medium">Backend</p><p className="mt-1 text-xs text-white/[.35]">Node · Express · APIs</p></div><div className="rounded-2xl border border-white/[.07] bg-black/10 p-4"><Database className="text-[#9b5cff]" /><p className="mt-4 text-sm font-medium">Data</p><p className="mt-1 text-xs text-white/[.35]">MongoDB · MySQL</p></div></div></div></Reveal></div></section>

    <section id="skills" className="border-y border-white/[.06] bg-white/[.015] border border-orange-500"><div className="mx-auto max-w-7xl px-5 py-28 md:px-8"><Reveal><p className="mono text-xs uppercase tracking-[.28em] text-[#9b5cff]">02 / skills</p><h2 className="mt-3 text-4xl font-bold md:text-6xl">My toolbox.</h2></Reveal><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{Object.entries(skills).map(([group, list], i) => <Reveal delay={i * .05} key={group}><div className="rounded-[28px] border border-white/[.07] bg-[#0e0c13] p-6"><p className="text-sm font-semibold">{group}</p><div className="mt-5 flex flex-wrap gap-2">{list.map(skill => <span key={skill} className="rounded-xl border border-white/[.07] px-3 py-2 text-xs text-white/[.55] transition hover:border-[#9b5cff]/40 hover:text-white">{skill}</span>)}</div></div></Reveal>)}</div></div></section>

    <section id="experience" className="mx-auto max-w-7xl px-5 py-28 md:px-8 border border-green-500"><Reveal><p className="mono text-xs uppercase tracking-[.28em] text-[#d6ff3f]">03 / experience</p><h2 className="mt-3 text-4xl font-bold md:text-6xl">A timeline, not a résumé dump.</h2></Reveal><div className="mt-12 grid gap-4">{timeline.map((item, i) => <Reveal key={item.year} delay={i * .06}><div className="grid gap-4 rounded-[26px] border border-white/[.07] bg-[#111017] p-6 md:grid-cols-[180px_1fr_auto] md:items-center"><p className="mono text-xs text-white/[.3]">{item.year}</p><div><p className="text-lg font-semibold">{item.role}</p><p className="mt-1 text-sm text-[#9b5cff]">{item.company}</p><p className="mt-3 max-w-2xl text-sm leading-6 text-white/[.45]">{item.desc}</p></div><span className="rounded-full border border-[#d6ff3f]/20 bg-[#d6ff3f]/5 px-3 py-1 text-[10px] uppercase tracking-[.14em] text-[#dfff80]">building</span></div></Reveal>)}</div></section>

    <section className="mx-auto max-w-7xl px-5 pb-28 md:px-8 border border-blue-500"><Reveal><div className="overflow-hidden rounded-[36px] border border-[#9b5cff]/25 bg-gradient-to-br from-[#171022] to-[#0f0c13] p-7 md:p-10"><div className="flex flex-col justify-between gap-10 md:flex-row md:items-end"><div><p className="mono text-xs uppercase tracking-[.28em] text-white/[.35]">04 / services</p><h2 className="mt-3 max-w-2xl text-4xl font-bold md:text-5xl">Good software is a conversation between product, code and people.</h2></div><Link href="#contact" className="inline-flex w-fit rounded-full bg-[#d6ff3f] px-5 py-3 text-sm font-bold text-black">Let's talk <ArrowUpRight size={16} /></Link></div><div className="mt-10 grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-white/[.03] p-5"><p className="font-semibold">01 / Build</p><p className="mt-2 text-sm leading-6 text-white/[.45]">Full-stack web apps with a production-ready foundation.</p></div><div className="rounded-2xl bg-white/[.03] p-5"><p className="font-semibold">02 / Refine</p><p className="mt-2 text-sm leading-6 text-white/[.45]">Turn rough product ideas into calm, expressive experiences.</p></div><div className="rounded-2xl bg-white/[.03] p-5"><p className="font-semibold">03 / Scale</p><p className="mt-2 text-sm leading-6 text-white/[.45]">Architecture, performance and data patterns that age well.</p></div></div></div></Reveal></section>

    <section className="border-t border-white/[.06] bg-[#0c0a10] border border-green-500"><div className="mx-auto max-w-7xl px-5 py-28 md:px-8"><Reveal><div className="flex items-end justify-between gap-6"><div><p className="mono text-xs uppercase tracking-[.28em] text-[#9b5cff]">05 / notes</p><h2 className="mt-3 text-4xl font-bold md:text-6xl">From the notebook.</h2></div><Link href="/blog" className="hidden rounded-full border border-white/[.1] px-5 py-2.5 text-xs text-white/[.65] md:inline-flex">Read all notes <ArrowUpRight size={14} /></Link></div></Reveal><div className="mt-10 grid gap-4">{posts.map((post: any, i: number) => <Reveal key={post._id} delay={i * .05}><Link data-cursor href={`/blog/${post.slug}`} className="group grid gap-4 rounded-[25px] border border-white/[.07] bg-[#111017] p-6 transition hover:border-[#9b5cff]/35 md:grid-cols-[110px_1fr_auto] md:items-center"><p className="mono text-xs text-white/[.25]">0{i + 1}</p><div><div className="flex flex-wrap gap-2">{post.tags?.slice(0, 3).map((t: string) => <span key={t} className="text-[10px] uppercase tracking-[.14em] text-[#9b5cff]">#{t}</span>)}</div><h3 className="mt-2 text-xl font-semibold group-hover:text-[#d6ff3f]">{post.title}</h3><p className="mt-2 text-sm text-white/[.4]">{post.excerpt}</p></div><ArrowUpRight size={20} className="text-white/[.25] transition group-hover:translate-x-1 group-hover:-translate-y-1 group-hover:text-white" /></Link></Reveal>)}</div></div></section>

    <section id="contact" className="mx-auto max-w-7xl px-5 py-28 md:px-8 border border-white-500"><Reveal><div className="grid gap-8 lg:grid-cols-[.85fr_1.15fr]"><div><p className="mono text-xs uppercase tracking-[.28em] text-[#d6ff3f]">06 / contact</p><h2 className="mt-4 max-w-xl text-5xl font-black tracking-[-.04em] md:text-7xl">Have a bold idea?<br /><span className="text-[#9b5cff]">Let's make it real.</span></h2><p className="mt-6 max-w-lg text-sm leading-7 text-white/[.45]">Whether it's a new product, a redesign, or a tricky engineering problem, send the brief. No corporate fog machine required.</p><div className="mt-9 space-y-4 text-sm text-white/[.55]"><div className="flex items-center gap-3"><Mail size={17} className="text-[#9b5cff]" /> hello@saksham.dev</div><div className="flex items-center gap-3"><MapPin size={17} className="text-[#d6ff3f]" /> India / Remote</div><div className="flex items-center gap-3"><ExternalLink size={17} className="text-[#9b5cff]" /> linkedin.com/in/saksham-demo</div></div></div><div className="rounded-[32px] border border-white/[.07] bg-[#111017] p-6 md:p-8"><ContactForm /></div></div></Reveal></section>

    <footer className="border-t border-white/[.06] border border-green-500"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-4 px-5 py-8 text-xs text-white/[.3] md:flex-row md:px-8"><p>© {new Date().getFullYear()} Saksham. Built with intent.</p><div className="flex items-center gap-5"><Link href="/privacy">Privacy</Link><Link href="/admin/login">Admin</Link><span className="mono">v1.0</span></div></div></footer>
  </main>;
}
